name: Build and Deploy

on:
    push:
        branches:
            - main

defaults:
    run:
        shell: bash

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            TZ: Asia/Tokyo
        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                submodules: recursive
                fetch-depth: 0
            - name: Setup bun
              uses: oven-sh/setup-bun@v2
            - name: Setup node
              uses: actions/setup-node@v6
              with:
                node-version: lts/*
            - name: Install dependencies
              run: bun install
            - name: Build
              run: bun run build
            - name: Deploy
              uses: cloudflare/wrangler-action@v3
              with:
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                wranglerVersion: '4.72.0'
                packageManager: bun
                command: deploy